### ISSUE TITLE
Have a meeting with Designsystemet

### ISSUE THREAD

**Issue by vnys** [equinor/design-system-css#7]
In order to create a scalable colour system we need to generate colour families programmatically. To gather some insight from somebody who already does that, let’s have a conversation with the designers from [Designsystemet](https://www.designsystemet.no/).

- [x] Call for meeting
- [x] Write a summary

**Comment by BirteThornquist** [comment]
A summary from the meeting is written  [here](https://statoilsrm.sharepoint.com/:w:/r/sites/Designsystem/Shared%20Documents/General/EDS%202.0%20Insights%20and%20Meeting%20Notes/Meeting%20with%20Designsystemet%20about%20their%20color%20generating%20app.docx?d=w9fac6b766c1c416ba123fdb2948f891e&csf=1&web=1&e=dmZ2M1)
